sudo: false
language: node_js
notifications:
  email: false
node_js:
  - lts/*
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
